In [3]:
import numpy as np
import pandas as pd

In [14]:
import numpy as np
import pandas as pd

observations = 1000
# generate random data
xs = np.random.uniform(low=-10,high=10,size=(observations,2))
zs = np.random.uniform(-10,10,(observations,2))
inputs = np.column_stack((xs,zs))
noise = np.random.uniform(-1,1,(observations,2))

targets = 2*xs - 3*zs + 5 + noise



In [15]:
# initialize variables

init_range = 0.1
weights = np.random.uniform(-init_range,init_range,size=(4,2))
bias = np.random.uniform(-init_range,init_range,size = 2)

In [16]:
# set learning rate
learning_rate = 0.02

In [17]:
# train model
for i in range (100):
    output = np.dot(inputs,weights) + bias
    deltas = output - targets
    loss = np.sum(deltas**2)/2/observations  #loss per observation
    print(loss)
    deltas_scaled = deltas/observations
    weights = weights - learning_rate * np.dot(inputs.T,deltas_scaled)
    bias = bias - learning_rate * np.sum(deltas_scaled)
    print(weights,bias)

474.16078091028345
[[ 1.51612163 -0.01895878]
 [ 0.07754987  1.3009779 ]
 [-2.1825263   0.01725067]
 [ 0.0666618  -1.9347326 ]] [0.17413241 0.18845747]
65.83078019118109
[[ 1.88157067e+00 -2.52353761e-03]
 [ 4.37704325e-02  1.75189227e+00]
 [-2.78245889e+00 -3.82999434e-03]
 [ 6.00795167e-02 -2.61658317e+00]] [0.36197731 0.37630237]
25.856437854872855
[[ 1.97257034  0.00665751]
 [ 0.01910649  1.91221485]
 [-2.95075189 -0.01074655]
 [ 0.04458597 -2.84836545]] [0.54451282 0.55883788]
20.341792240391488
[[ 1.9947431   0.010694  ]
 [ 0.00720877  1.96918659]
 [-2.9986157  -0.01261675]
 [ 0.03534086 -2.92781017]] [0.72063757 0.73496263]
18.39954822645447
[[ 1.99988280e+00  1.22230607e-02]
 [ 2.27382139e-03  1.98947648e+00]
 [-3.01233206e+00 -1.28866963e-02]
 [ 3.05973514e-02 -2.95559566e+00]] [0.89006357 0.90438863]
16.943426887897648
[[ 2.00089231e+00  1.26835542e-02]
 [ 4.24805195e-04  1.99676465e+00]
 [-3.01619493e+00 -1.27076084e-02]
 [ 2.80061932e-02 -2.96582122e+00]] [1.05284796 1.0671